# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cfg_messages.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='cfg_messages.proto',
    package='cfg_messages',
    serialized_pb=_b(
        '\n\x12\x63\x66g_messages.proto\x12\x0c\x63\x66g_messages\"$\n\x05Param\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"u\n\x13\x43onfigParamsRequest\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x10\n\x08receiver\x18\x02 \x02(\t\x12\x13\n\x0bparam_names\x18\x03 \x03(\t\x12\'\n\next_params\x18\x04 \x03(\x0b\x32\x13.cfg_messages.Param\"~\n\x0c\x43onfigParams\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12#\n\x06params\x18\x03 \x03(\x0b\x32\x13.cfg_messages.Param\x12\'\n\next_params\x18\x04 \x03(\x0b\x32\x13.cfg_messages.Param\"\x1f\n\x0cPeerIdentity\x12\x0f\n\x07peer_id\x18\x01 \x02(\t\".\n\x0ePeerReadyQuery\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x65ps\x18\x02 \x03(\t\"8\n\x0fPeerReadyStatus\x12\x10\n\x08receiver\x18\x01 \x02(\t\x12\x13\n\x0bpeers_ready\x18\x02 \x02(\x08\"@\n\x0b\x43onfigError\x12\x0f\n\x07rq_type\x18\x01 \x01(\t\x12\x11\n\terror_str\x18\x02 \x01(\t\x12\r\n\x05\x65rrno\x18\x03 \x01(\t\"9\n\x0fLauncherCommand\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x16\n\x0eserialized_msg\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_PARAM = _descriptor.Descriptor(
    name='Param',
    full_name='cfg_messages.Param',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='name', full_name='cfg_messages.Param.name', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='value', full_name='cfg_messages.Param.value', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=36,
    serialized_end=72,
)


_CONFIGPARAMSREQUEST = _descriptor.Descriptor(
    name='ConfigParamsRequest',
    full_name='cfg_messages.ConfigParamsRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='sender', full_name='cfg_messages.ConfigParamsRequest.sender', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='receiver', full_name='cfg_messages.ConfigParamsRequest.receiver', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='param_names', full_name='cfg_messages.ConfigParamsRequest.param_names', index=2,
            number=3, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='ext_params', full_name='cfg_messages.ConfigParamsRequest.ext_params', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=74,
    serialized_end=191,
)


_CONFIGPARAMS = _descriptor.Descriptor(
    name='ConfigParams',
    full_name='cfg_messages.ConfigParams',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='sender', full_name='cfg_messages.ConfigParams.sender', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='receiver', full_name='cfg_messages.ConfigParams.receiver', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='params', full_name='cfg_messages.ConfigParams.params', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='ext_params', full_name='cfg_messages.ConfigParams.ext_params', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=193,
    serialized_end=319,
)


_PEERIDENTITY = _descriptor.Descriptor(
    name='PeerIdentity',
    full_name='cfg_messages.PeerIdentity',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='peer_id', full_name='cfg_messages.PeerIdentity.peer_id', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=321,
    serialized_end=352,
)


_PEERREADYQUERY = _descriptor.Descriptor(
    name='PeerReadyQuery',
    full_name='cfg_messages.PeerReadyQuery',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='sender', full_name='cfg_messages.PeerReadyQuery.sender', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='deps', full_name='cfg_messages.PeerReadyQuery.deps', index=1,
            number=2, type=9, cpp_type=9, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=354,
    serialized_end=400,
)


_PEERREADYSTATUS = _descriptor.Descriptor(
    name='PeerReadyStatus',
    full_name='cfg_messages.PeerReadyStatus',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='receiver', full_name='cfg_messages.PeerReadyStatus.receiver', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='peers_ready', full_name='cfg_messages.PeerReadyStatus.peers_ready', index=1,
            number=2, type=8, cpp_type=7, label=2,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=402,
    serialized_end=458,
)


_CONFIGERROR = _descriptor.Descriptor(
    name='ConfigError',
    full_name='cfg_messages.ConfigError',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='rq_type', full_name='cfg_messages.ConfigError.rq_type', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='error_str', full_name='cfg_messages.ConfigError.error_str', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='errno', full_name='cfg_messages.ConfigError.errno', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=460,
    serialized_end=524,
)


_LAUNCHERCOMMAND = _descriptor.Descriptor(
    name='LauncherCommand',
    full_name='cfg_messages.LauncherCommand',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='sender', full_name='cfg_messages.LauncherCommand.sender', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='serialized_msg', full_name='cfg_messages.LauncherCommand.serialized_msg', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=526,
    serialized_end=583,
)

_CONFIGPARAMSREQUEST.fields_by_name['ext_params'].message_type = _PARAM
_CONFIGPARAMS.fields_by_name['params'].message_type = _PARAM
_CONFIGPARAMS.fields_by_name['ext_params'].message_type = _PARAM
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['ConfigParamsRequest'] = _CONFIGPARAMSREQUEST
DESCRIPTOR.message_types_by_name['ConfigParams'] = _CONFIGPARAMS
DESCRIPTOR.message_types_by_name['PeerIdentity'] = _PEERIDENTITY
DESCRIPTOR.message_types_by_name['PeerReadyQuery'] = _PEERREADYQUERY
DESCRIPTOR.message_types_by_name['PeerReadyStatus'] = _PEERREADYSTATUS
DESCRIPTOR.message_types_by_name['ConfigError'] = _CONFIGERROR
DESCRIPTOR.message_types_by_name['LauncherCommand'] = _LAUNCHERCOMMAND

Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), dict(
                                                 DESCRIPTOR=_PARAM,
                                                 __module__='cfg_messages_pb2'
                                                 # @@protoc_insertion_point(class_scope:cfg_messages.Param)
                                                 ))
_sym_db.RegisterMessage(Param)

ConfigParamsRequest = _reflection.GeneratedProtocolMessageType('ConfigParamsRequest', (_message.Message,), dict(
                                                               DESCRIPTOR=_CONFIGPARAMSREQUEST,
                                                               __module__='cfg_messages_pb2'
                                                               # @@protoc_insertion_point(class_scope:cfg_messages.ConfigParamsRequest)
                                                               ))
_sym_db.RegisterMessage(ConfigParamsRequest)

ConfigParams = _reflection.GeneratedProtocolMessageType('ConfigParams', (_message.Message,), dict(
                                                        DESCRIPTOR=_CONFIGPARAMS,
                                                        __module__='cfg_messages_pb2'
                                                        # @@protoc_insertion_point(class_scope:cfg_messages.ConfigParams)
                                                        ))
_sym_db.RegisterMessage(ConfigParams)

PeerIdentity = _reflection.GeneratedProtocolMessageType('PeerIdentity', (_message.Message,), dict(
                                                        DESCRIPTOR=_PEERIDENTITY,
                                                        __module__='cfg_messages_pb2'
                                                        # @@protoc_insertion_point(class_scope:cfg_messages.PeerIdentity)
                                                        ))
_sym_db.RegisterMessage(PeerIdentity)

PeerReadyQuery = _reflection.GeneratedProtocolMessageType('PeerReadyQuery', (_message.Message,), dict(
                                                          DESCRIPTOR=_PEERREADYQUERY,
                                                          __module__='cfg_messages_pb2'
                                                          # @@protoc_insertion_point(class_scope:cfg_messages.PeerReadyQuery)
                                                          ))
_sym_db.RegisterMessage(PeerReadyQuery)

PeerReadyStatus = _reflection.GeneratedProtocolMessageType('PeerReadyStatus', (_message.Message,), dict(
                                                           DESCRIPTOR=_PEERREADYSTATUS,
                                                           __module__='cfg_messages_pb2'
                                                           # @@protoc_insertion_point(class_scope:cfg_messages.PeerReadyStatus)
                                                           ))
_sym_db.RegisterMessage(PeerReadyStatus)

ConfigError = _reflection.GeneratedProtocolMessageType('ConfigError', (_message.Message,), dict(
                                                       DESCRIPTOR=_CONFIGERROR,
                                                       __module__='cfg_messages_pb2'
                                                       # @@protoc_insertion_point(class_scope:cfg_messages.ConfigError)
                                                       ))
_sym_db.RegisterMessage(ConfigError)

LauncherCommand = _reflection.GeneratedProtocolMessageType('LauncherCommand', (_message.Message,), dict(
                                                           DESCRIPTOR=_LAUNCHERCOMMAND,
                                                           __module__='cfg_messages_pb2'
                                                           # @@protoc_insertion_point(class_scope:cfg_messages.LauncherCommand)
                                                           ))
_sym_db.RegisterMessage(LauncherCommand)


# @@protoc_insertion_point(module_scope)
